=== wenky/owasp-jsp-testing-tool/resources/attacks.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="attacks">

		<xsd:complexType>

			<xsd:sequence>
				<xsd:element name="attack" type="attackType" maxOccurs="unbounded"
					minOccurs="1" >
				</xsd:element>
			</xsd:sequence>

		</xsd:complexType>
	</xsd:element>
	
	<xsd:complexType name="attackType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="display-name" type="xsd:string"/>
			<xsd:element name="attack-string" type="xsd:string"/>
		</xsd:sequence>	
	</xsd:complexType>	
</xsd:schema>

=== wenky/owasp-jsp-testing-tool/owasp-jsp-testing-tool-v0.5/resources/attacks.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<attacks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="attacks.xsd">
	<attack>
		<name>raw</name>
		<display-name>Tag Based</display-name>
		<attack-string>&lt;script&gt;x()&lt;/script&gt;</attack-string>
	</attack>
	<attack>
		<name>css</name>
		<display-name>CSS Based</display-name>
		<attack-string>c:expression(x());</attack-string>
	</attack>
	<attack>
		<name>quote_attribute</name>
		<display-name>Quote Attribute Based</display-name>
		<attack-string>&quot; onmouseover=&quot;x()</attack-string>
	</attack>
	<attack>
		<name>apos_attribute</name>
		<display-name>Apostrophe Attribute Based</display-name>
		<attack-string>' onmouseover='x()</attack-string>
	</attack>	
	<attack>
		<name>url</name>
		<display-name>URL Based</display-name>
		<attack-string>javascript:x()</attack-string>
	</attack>
	<attack>
		<name>event</name>
		<display-name>Event Based</display-name>
		<attack-string>x()</attack-string>
	</attack>
</attacks>
